/**
 * 測試用的迷你考卷：每種作答介面各一個題組（詞彙、綜合測驗、文意選填、閱讀＋refers_to、混合題、中譯英、作文），
 * 內容取自 115 學測並大幅縮短。只給測試用，App 不會匯入這個檔案。
 */
import type { Exam, ExamIndex } from '../../data/exams';

export const MINI_EXAM: Exam = {
  schema: 'gsat-exam/v1.1',
  id: 'gsat-115',
  exam: 'gsat',
  year: 115,
  session: 'regular',
  title: '115學年度學科能力測驗英文考科',
  time_minutes: 100,
  full_score: 100,
  target: null,
  verified: true,
  official_files: [
    { kind: 'paper', subkind: 'paper', label: '試題（PDF）', format: 'pdf', url: 'https://www.ceec.edu.tw/paper.pdf' },
    { kind: 'scoring', subkind: 'scoring', label: '非選擇題評分原則', format: 'pdf', url: 'https://www.ceec.edu.tw/scoring.pdf' },
  ],
  sections: [
    {
      id: 's1',
      type: 'vocabulary',
      title: '一、詞彙題（占2分）',
      part: '選擇題',
      instructions: '說明︰第1題至第2題為單選題，每題1分。',
      points_total: 2,
      groups: [
        {
          id: 's1g1',
          passage: null,
          passage_parts: null,
          figures: [],
          options_bank: null,
          tags: null,
          questions: [
            {
              no: 1,
              label: '1',
              mode: 'single_choice',
              stem: 'The mayor has such a ______ schedule that it takes weeks to arrange an interview with her.',
              options: { A: 'hasty', B: 'tight', C: 'diligent', D: 'routine' },
              answer: 'B',
              accepted_answers: null,
              points: 1,
              stats: { correct_rate: 0.57, high_group: 0.87, low_group: 0.33, discrimination: 0.54, option_rates: { A: 0.12, B: 0.57, C: 0.12, D: 0.19 } },
              tags: { test_point: 'collocation', key_phrase: 'tight schedule' },
            },
            {
              no: 2,
              label: '2',
              mode: 'single_choice',
              stem: 'Jane started as an ______ art designer.',
              options: { A: 'official', B: 'instant', C: 'amateur', D: 'elementary' },
              answer: 'C',
              accepted_answers: null,
              points: 1,
              stats: null,
              tags: {},
              scoring_exception: { type: 'all_credit', note: '測試用送分題' },
            },
          ],
        },
      ],
    },
    {
      id: 's2',
      type: 'cloze',
      title: '二、綜合測驗（占2分）',
      part: '選擇題',
      instructions: '說明︰第11題至第12題為單選題，每題1分。',
      points_total: 2,
      groups: [
        {
          id: 's2g1',
          passage: 'White rhinoceroses, [[11]], do the same thing.\nThey [[12]] through dung piles.',
          passage_parts: null,
          figures: [],
          options_bank: null,
          tags: { topic: 'rhinos', genre: 'expository', sdgs: [15], text_format: 'continuous' },
          questions: [
            {
              no: 11,
              label: '11',
              mode: 'single_choice',
              stem: null,
              options: { A: 'what is more', B: 'it turns out', C: 'in other words', D: 'all in all' },
              answer: 'B',
              accepted_answers: null,
              points: 1,
              stats: { correct_rate: 0.29, option_rates: { A: 0.18, B: 0.29, C: 0.32, D: 0.22 } },
              tags: {},
            },
            {
              no: 12,
              label: '12',
              mode: 'single_choice',
              stem: null,
              options: { A: 'demonstrate', B: 'immigrate', C: 'communicate', D: 'manipulate' },
              answer: 'C',
              accepted_answers: null,
              points: 1,
              stats: null,
              tags: {},
            },
          ],
        },
      ],
    },
    {
      id: 's3',
      type: 'word_bank',
      title: '三、文意選填（占3分）',
      part: '選擇題',
      instructions: '說明：第21題至第23題為單選題，每題1分。',
      points_total: 3,
      groups: [
        {
          id: 's3g1',
          passage: 'Taking a nap is by no means [[21]].\nNaps help us [[22]] memories and [[23]] on work.',
          passage_parts: null,
          figures: [],
          options_bank: { A: 'retain', B: 'depend on', C: 'atmosphere', D: 'focus', E: 'lazy' },
          tags: { topic: 'naps', genre: 'expository', sdgs: [3], text_format: 'continuous' },
          questions: [
            { no: 21, label: '21', mode: 'bank_choice', stem: null, options: null, answer: 'E', accepted_answers: null, points: 1, stats: null, tags: {} },
            { no: 22, label: '22', mode: 'bank_choice', stem: null, options: null, answer: 'A', accepted_answers: null, points: 1, stats: null, tags: {} },
            { no: 23, label: '23', mode: 'bank_choice', stem: null, options: null, answer: 'D', accepted_answers: null, points: 1, stats: null, tags: {} },
          ],
        },
      ],
    },
    {
      id: 's4',
      type: 'reading',
      title: '四、閱讀測驗（占2分）',
      part: '選擇題',
      instructions: '說明︰第40題為單選題，每題2分。',
      points_total: 2,
      groups: [
        {
          id: 's4g1',
          passage: 'Defenders built <u>stairs</u> in towers. Attackers found them hard to climb.\nThe stairs turned clockwise.',
          passage_parts: null,
          figures: [{ kind: 'table', caption: '樓梯資料', description: '兩欄表格', rows: [['Castle', 'Turn'], ['A', 'clockwise']] }],
          options_bank: null,
          tags: { topic: 'stairs', genre: 'expository', sdgs: [], text_format: 'mixed' },
          questions: [
            {
              no: 40,
              label: '40',
              mode: 'single_choice',
              stem: 'What does “them” in the first paragraph refer to?',
              options: { A: 'Stairs.', B: 'Towers.', C: 'Attackers.', D: 'Defenders.' },
              answer: 'A',
              accepted_answers: null,
              points: 2,
              stats: { correct_rate: 0.38 },
              tags: { item_type: 'reference' },
              refers_to: { text: 'them', occurrence: 1, note: null },
            },
          ],
        },
      ],
    },
    {
      id: 's5',
      type: 'mixed',
      title: '第貳部分、混合題（占8分）',
      part: '混合題',
      instructions: '說明︰本部分共有1題組。',
      points_total: 8,
      groups: [
        {
          id: 's5g1',
          passage: 'Wonder Village mixes tradition with innovation.',
          passage_parts: [
            { label: 'A', title: 'Oh Eco', text: 'Recycled plastic sunglasses.' },
            { label: 'B', title: 'After Work', text: 'Coffee and books.' },
          ],
          figures: [],
          options_bank: null,
          tags: { topic: 'village', genre: 'expository', sdgs: [], text_format: 'multi_text' },
          questions: [
            {
              no: 47,
              label: '47',
              mode: 'fill_in_blank',
              stem: '請從文章中找出單詞填入空格。\nTradition coexists with [[47]], and features are [[48]].',
              options: null,
              answer: 'innovation',
              accepted_answers: null,
              points: 2,
              stats: null,
              tags: {},
            },
            {
              no: 48,
              label: '48',
              mode: 'fill_in_blank',
              stem: '請從文章中找出單詞填入空格。\nTradition coexists with [[47]], and features are [[48]].',
              options: null,
              answer: 'blended',
              accepted_answers: null,
              points: 2,
              stats: null,
              tags: {},
            },
            {
              no: 49,
              label: '49',
              mode: 'multi_select',
              stem: 'Which stores sell these items?（多選題，4分）',
              options: { A: 'Oh Eco', B: 'After Work', C: 'Aroma Paradise', D: 'Something Different', E: 'Beyond World', F: 'The Pinery' },
              answer: ['A', 'D', 'E'],
              accepted_answers: null,
              points: 4,
              stats: { correct_rate: 0.55, full_correct_rate: 0.36, option_rates: { A: 0.73, B: 0.16, C: 0.23, D: 0.77, E: 0.51, F: 0.1 } },
              tags: {},
            },
          ],
        },
      ],
    },
    {
      id: 's6',
      type: 'translation',
      title: '一、中譯英（占4分）',
      part: '非選擇題',
      instructions: '說明：依題號將以下中文句子譯成英文。',
      points_total: 4,
      groups: [
        {
          id: 's6g1',
          passage: null,
          passage_parts: null,
          figures: [],
          options_bank: null,
          tags: null,
          questions: [
            {
              no: 1,
              label: '中譯英1',
              mode: 'translation',
              stem: '現在越來越多高中英文老師已經增加在課堂上使用英文的百分比。',
              options: null,
              // 公開資料檔的中譯英沒有 answer／accepted_answers（build-data.mjs 刪掉官方參考譯文，D8）。
              points: 4,
              stats: null,
              tags: { patterns: ['more and more'] },
            },
          ],
        },
      ],
    },
    {
      id: 's7',
      type: 'composition',
      title: '二、英文作文（占20分）',
      part: '非選擇題',
      instructions: '說明︰依提示寫一篇英文作文，文長至少120個單詞（words）。',
      points_total: 20,
      groups: [
        {
          id: 's7g1',
          passage: null,
          passage_parts: null,
          figures: [],
          options_bank: null,
          tags: null,
          questions: [
            {
              no: 1,
              label: '英文作文',
              mode: 'composition',
              stem: '提示︰請以寵物為主題，寫一篇英文作文，文分兩段。',
              options: null,
              answer: null,
              accepted_answers: null,
              points: 20,
              stats: null,
              tags: { essay_type: 'picture', paragraphs: 2, word_count: { min: 120, max: null, approx: null } },
            },
          ],
        },
      ],
    },
  ],
};

export const MINI_INDEX: ExamIndex = {
  version: 'test',
  count: 3,
  exams: [
    {
      id: 'gsat-115',
      exam: 'gsat',
      year: 115,
      session: 'regular',
      title: '115學年度學科能力測驗英文考科',
      time_minutes: 100,
      full_score: 100,
      target: null,
      verified: true,
      question_count: 53,
      has_stats: true,
      sections: [
        { id: 's1', type: 'vocabulary', title: '一、詞彙題（占10分）', question_count: 10, points_total: 10, has_stats: true },
        { id: 's6', type: 'mixed', title: '第貳部分、混合題（占10分）', question_count: 4, points_total: 10, has_stats: true },
      ],
    },
    {
      id: 'ast-109-makeup',
      exam: 'ast',
      year: 109,
      session: 'makeup',
      title: '109學年度指定科目考試（補考）英文考科',
      time_minutes: 80,
      full_score: 100,
      target: null,
      verified: true,
      question_count: 54,
      has_stats: false,
      sections: [{ id: 's1', type: 'vocabulary', title: '一、詞彙題（占10分）', question_count: 10, points_total: 10, has_stats: false }],
    },
    {
      id: 'ref-111',
      exam: 'reference',
      year: 111,
      session: 'regular',
      title: '學科能力測驗參考試卷（111學年度起適用）英文考科',
      time_minutes: 100,
      full_score: 100,
      target: 'gsat',
      verified: true,
      question_count: 53,
      has_stats: false,
      sections: [{ id: 's6', type: 'mixed', title: '第貳部分、混合題（占10分）', question_count: 4, points_total: 10, has_stats: false }],
    },
  ],
};

export const jsonResponse = (body: unknown) =>
  new Response(JSON.stringify(body), { headers: { 'Content-Type': 'application/json' } });
